"""Initial schema

Revision ID: 1650d0d9727d
Revises:
Create Date: 2026-08-15 10:37:42.927846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1650d0d9727d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('failed_threshold', sa.Integer(), nullable=False),
    sa.Column('minimum_users', sa.Integer(), nullable=False),
    sa.Column('window_threshold', sa.Integer(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('brute_force_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brute_force_ips_id'), 'brute_force_ips', ['id'], unique=False)
    op.create_table('ml_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('failure_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_anomalies_id'), 'ml_anomalies', ['id'], unique=False)
    op.create_table('multi_user_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('usernames', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_user_ips_id'), 'multi_user_ips', ['id'], unique=False)
    op.create_table('suspicious_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspicious_ips_id'), 'suspicious_ips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suspicious_ips_id'), table_name='suspicious_ips')
    op.drop_table('suspicious_ips')
    op.drop_index(op.f('ix_multi_user_ips_id'), table_name='multi_user_ips')
    op.drop_table('multi_user_ips')
    op.drop_index(op.f('ix_ml_anomalies_id'), table_name='ml_anomalies')
    op.drop_table('ml_anomalies')
    op.drop_index(op.f('ix_brute_force_ips_id'), table_name='brute_force_ips')
    op.drop_table('brute_force_ips')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
